spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5433/${DATABASE_NAME}?sslmode=disable
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true